### ISSUE TITLE
Place first realistic db file to datasette instance

### ISSUE THREAD

**Issue by antaldaniel** [dataobservatory-eu/observatory_workflow#15]
It is temporarily located here: 
[dmo.db](https://github.com/dataobservatory-eu/indicator/tree/master/data-raw)

@KKulma @bvitos 

With @pitkant  we try to create a basic set of indicators for all three observatories, and in the meantime, if necessary, debug the [indicator](https://github.com/dataobservatory-eu/indicator) package.  In the first weeks, only this package will harvest data, later we will ad a Python harvester for the Python-team.

**Comment by bvitos** [comment]
Instance currently running on http://34.226.91.55

**Comment by antaldaniel** [comment]
@bvitos , brillant, thank you!
