### ISSUE TITLE
Submission presentation: observatory overview

### ISSUE THREAD

**Issue by antaldaniel** [dataobservatory-eu/observatory_workflow#7]
1. Please create a few collages from the competitor observatories' screenshots in different sizes, aspect ratios. 
We usually need 1:1, 3:2 and 16:9. It is only a collage, we should have several version to chooes from. 

2. Please create a folder and a csv table. The folder should have thumbnails of the screenshots, either in 160x160 size, or in any aspect ratio with the width fixed at 160px. 
screenshot_file, observatory_url, observatory name
Car_Observatory.png, http://cars.eu, European Car Observatory 

format (no matter if the files are jpg or png, and how the filenames are, just to create a  thumbnail table like this 
https://listenlocal.community/post/2020-12-17-demo-slovak-music-database/

**Comment by bvitos** [comment]
Should I push it to the main repo?

**Comment by antaldaniel** [comment]
If you can, just make please a plot subfolder.

**Comment by bvitos** [comment]
OK, it's under Plot/Observatory_Overview
